# version number
version: 1.0.{build}-{branch}

# build configurations
configuration: Release

# enable AssemblyInfo.cs patching with build version number
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore src\Markdig.SyntaxHighlighting.sln

cache:
  - packages -> **\packages.config  # preserve "packages" directory

build:
  # enable MSBuild parallel builds
  parallel: true
  project: src\Markdig.SyntaxHighlighting.sln
  publish_nuget: true
  publish_nuget_symbols: true
